apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
spec:
  replicas: 1 # how many instances of the voting app
  selector: # after it creates pod, which pods should it watch over
    matchLabels:
      app: vote
  template: # what pod are you interested in creating
    metadata:
      name: vote
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
              name: vote