apiVersion: v1
kind: Pod
metadata:
  name: low-prio-pod
  labels:
    app: low-prio-pod
spec:
  containers:
    - name: low-prio-pod
      image: nginx
      command:
      - sleep 1000
  priorityClass: low-priority