apiVersion: v1
kind: Service
metadata:
  - name: db # instead of having to remember IP of Service, you can send to DNS name (redis)
    labels:
      app: db
spec:
  ports: # the type is ClusterIP since that is only internal to our app, but that is the default type so we don't need to include
    - name: "db-service"
      port: 5432 # port that service is listening on
      targetPort: 5432 # port should it forward to on the container
  selector: # what port should it forward traffic to
    app: db # forward to any pod with this label